
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
     - ./init:/docker-entrypoint-initdb.d 

  node-service:
    build: ./docker/api
    environment:
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

    depends_on:
      - db
    

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "/c/Users/daljo/docker-challenge-template/challenge3/docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - node-service
